# permissions for end users to view operators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-viewer-role
rules:
- apiGroups:
  - olm.operatorframework.io
  resources:
  - operators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - olm.operatorframework.io
  resources:
  - operators/status
  verbs:
  - get
