# permissions for end users to edit pathselectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pathselector-editor-role
rules:
- apiGroups:
  - olm.operatorframework.io
  resources:
  - pathselectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - olm.operatorframework.io
  resources:
  - pathselectors/status
  verbs:
  - get
