# permissions for end users to view pathselectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pathselector-viewer-role
rules:
- apiGroups:
  - olm.operatorframework.io
  resources:
  - pathselectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - olm.operatorframework.io
  resources:
  - pathselectors/status
  verbs:
  - get
