# permissions for end users to edit pathselectorclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pathselectorclass-editor-role
rules:
- apiGroups:
  - olm.operatorframework.io
  resources:
  - pathselectorclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - olm.operatorframework.io
  resources:
  - pathselectorclasses/status
  verbs:
  - get
