# permissions for end users to view pathselectorclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pathselectorclass-viewer-role
rules:
- apiGroups:
  - olm.operatorframework.io
  resources:
  - pathselectorclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - olm.operatorframework.io
  resources:
  - pathselectorclasses/status
  verbs:
  - get
