
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - olm.operatorframework.io
  resources:
  - operators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - olm.operatorframework.io
  resources:
  - operators/finalizers
  verbs:
  - update
- apiGroups:
  - olm.operatorframework.io
  resources:
  - operators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - olm.operatorframework.io
  resources:
  - pathselectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - olm.operatorframework.io
  resources:
  - pathselectors/finalizers
  verbs:
  - update
- apiGroups:
  - olm.operatorframework.io
  resources:
  - pathselectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - olm.operatorframework.io
  resources:
  - subscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - olm.operatorframework.io
  resources:
  - subscriptions/finalizers
  verbs:
  - update
- apiGroups:
  - olm.operatorframework.io
  resources:
  - subscriptions/status
  verbs:
  - get
  - patch
  - update
