- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/constraint/properties/all/items
  value:
    type: object
    additionalProperties: true

- op: replace
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/constraint/properties/any/items
  value: 
    type: object
    additionalProperties: true
