apiVersion: olm.operatorframework.io/v1
kind: Subscription
metadata:
  name: foo
spec:
  approval: Automatic
  constraint:
    all:
    - selector:
        matchLabels:
          minor: "0.1"
    any:
    - channel: alpha
  package: foo
