apiVersion: olm.operatorframework.io/v1
kind: Subscription
metadata:
  name: app-operator
spec:
  approval: Automatic
  constraint:
    all:
    - versionRange: ">=0.1.0 <0.2.0"
    any:
    - channel: alpha
  package: app-operator
